# Generated by Django 3.2.5 on 2021-07-18 08:57

from django.db import migrations, models
import pe.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PsmcExcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('date', models.DateTimeField()),
                ('status', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('file', models.FilePathField(blank=True, default=None, null=True, path=pe.models.psmc_folder)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'pe_psmc_excel',
                'ordering': ['date'],
            },
        ),
    ]
