# Generated by Django 3.2.6 on 2021-08-03 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=79)),
                ('dep_id', models.CharField(max_length=79)),
                ('dep_name', models.CharField(max_length=79)),
                ('email', models.EmailField(blank=True, default=None, max_length=254, null=True)),
                ('group', models.CharField(blank=True, default=None, max_length=1, null=True)),
            ],
            options={
                'db_table': 'employee',
            },
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['name'], name='employee_name_7aabaa_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['group'], name='employee_group_e2baac_idx'),
        ),
    ]
