# Generated by Django 3.2.5 on 2021-08-01 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_employee_employee_name_7aabaa_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='dep_id',
            field=models.CharField(default='', max_length=79),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='dep_name',
            field=models.CharField(default='', max_length=79),
            preserve_default=False,
        ),
    ]
