# Generated by Django 3.2.5 on 2021-07-24 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gateway',
            name='floor',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='gateway',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AddIndex(
            model_name='gateway',
            index=models.Index(fields=['date'], name='hr_gateway_date_7d03d9_idx'),
        ),
        migrations.AddIndex(
            model_name='gateway',
            index=models.Index(fields=['floor'], name='hr_gateway_floor_d8b13a_idx'),
        ),
        migrations.AddIndex(
            model_name='gateway',
            index=models.Index(fields=['door'], name='hr_gateway_door_acedb3_idx'),
        ),
    ]
